<html>
<link rel="stylesheet" type="text/css" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />

    <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js'></script>
    <script type='text/javascript' src='http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js'></script>
  </head>

  <body>

    <div id="map" style="width:100%; height: 100%; border: 0 px ; position:absolute"></div>

    <script type='text/javascript' src='maps/remote.json'></script>
    <script type='text/javascript' src='maps/location.js'></script>
  </body>
</html>
